spring:
  server:
    port: 8000
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/ecommerce}
    username: ${DBMS_USERNAME:docker_database}
    password: ${DBMS_PASSWORD:0011246}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  prefix: "api/v1"
app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080